apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
  labels:
    app: flask-app
  annotations:
    image.toolkit.fluxcd.io/image-refs: saip1106/flask-fluxcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: saip1106/flask-fluxcd:16 # {"$imagepolicy": "flux-system:podinfo"}
          ports:
            - containerPort: 5000
